batch_size: 128
clip_gradient_norm: 1
commit_hash:
data_dir: data
dataset: generic
device: cuda:0
dynamic_inputs:
- dayl
- prcp
- srad
- swe
- tmax
- tmin
- vp
epochs: 100
experiment_name: LSTM_Regional_Area_Norm
head: regression
hidden_size: 256
img_log_dir: 
  C:\Users\ybrot\Desktop\course\UROP\GAGEii_modeling\runs\EA-LSTM_Regional_0604_152713\img_log
initial_forget_bias: 3
learning_rate:
  0: 0.0001
log_interval: 5
log_tensorboard: true
loss: MSE
metrics:
- NSE
model: lstm
num_workers: 8
number_of_basins: 780
optimizer: Adam
output_activation: linear
output_dropout: 0.3
package_version: 1.11.0
predict_last_n: 1
run_dir: 
  C:\Users\ybrot\Desktop\course\UROP\GAGEii_modeling\runs
save_validation_results: true
save_weights_every: 1
seed: 316926
seq_length: 365
static_attributes:
- sgr_dk_sav
- glc_pc_s06
- nli_ix_sav
- glc_pc_s04
- glc_pc_s02
- glc_pc_s09
- swc_pc_s09
- ele_mt_smx
- tbi_cl_smj
- swc_pc_s01
- swc_pc_s02
- swc_pc_s03
- swc_pc_s04
- swc_pc_s05
- swc_pc_s06
- swc_pc_s07
- swc_pc_s08
- crp_pc_sse
- glc_pc_s22
- glc_pc_s20
- wet_pc_sg1
- wet_pc_sg2
- pac_pc_sse
- swc_pc_s10
- swc_pc_s11
- swc_pc_s12
- clz_cl_smj
- gwt_cm_sav
- glc_pc_s18
- hft_ix_s93
- glc_pc_s15
- ire_pc_sse
- glc_pc_s16
- glc_pc_s13
- glc_pc_s14
- glc_pc_s11
- glc_pc_s12
- glc_pc_s10
- kar_pc_sse
- slp_dg_sav
- tmp_dc_s07
- tmp_dc_s08
- tmp_dc_s05
- tmp_dc_s06
- tmp_dc_s09
- for_pc_sse
- aet_mm_s06
- aet_mm_s05
- aet_mm_s08
- aet_mm_s07
- aet_mm_s09
- tmp_dc_s10
- tmp_dc_s11
- aet_mm_s02
- aet_mm_s01
- tmp_dc_s12
- aet_mm_s04
- aet_mm_s03
- lit_cl_smj
- tmp_dc_s03
- tmp_dc_s04
- tmp_dc_s01
- tmp_dc_s02
- cls_cl_smj
- pre_mm_syr
- pnv_pc_s04
- pnv_pc_s05
- rdd_mk_sav
- ele_mt_smn
- pnv_pc_s08
- pnv_pc_s09
- pnv_pc_s06
- wet_cl_smj
- snw_pc_syr
- pnv_pc_s10
- cmi_ix_syr
- pet_mm_s11
- pet_mm_s12
- pet_mm_s10
- tmp_dc_smn
- wet_pc_s02
- wet_pc_s03
- wet_pc_s01
- hdi_ix_sav
- glc_cl_smj
- swc_pc_syr
- hft_ix_s09
- soc_th_sav
- gdp_ud_sav
- gdp_ud_ssu
- tmp_dc_smx
- cly_pc_sav
- pet_mm_s02
- pet_mm_s03
- pet_mm_s01
- snw_pc_smx
- ppd_pk_sav
- pet_mm_s08
- aet_mm_s11
- pet_mm_s09
- aet_mm_s10
- pet_mm_s06
- pet_mm_s07
- aet_mm_s12
- pet_mm_s04
- pet_mm_s05
- inu_pc_slt
- ero_kh_sav
- aet_mm_syr
- cmi_ix_s10
- cmi_ix_s11
- cmi_ix_s12
- ari_ix_sav
- tmp_dc_syr
- tec_cl_smj
- fmh_cl_smj
- inu_pc_smn
- pnv_cl_smj
- pre_mm_s08
- pre_mm_s09
- run_mm_syr
- pre_mm_s06
- pre_mm_s07
- pre_mm_s04
- pre_mm_s05
- snd_pc_sav
- pre_mm_s02
- pre_mm_s03
- ele_mt_sav
- pre_mm_s01
- urb_pc_sse
- lka_pc_sse
- pre_mm_s10
- snw_pc_s01
- snw_pc_s02
- snw_pc_s03
- snw_pc_s04
- snw_pc_s05
- snw_pc_s06
- snw_pc_s07
- snw_pc_s08
- snw_pc_s09
- inu_pc_smx
- pre_mm_s11
- pre_mm_s12
- cmi_ix_s07
- cmi_ix_s08
- cmi_ix_s05
- cmi_ix_s06
- cmi_ix_s09
- snw_pc_s10
- snw_pc_s11
- snw_pc_s12
- cmi_ix_s03
- cmi_ix_s04
- cmi_ix_s01
- cmi_ix_s02
- pst_pc_sse
- dis_m3_pmn
- dis_m3_pmx
- dis_m3_pyr
- lkv_mc_usu
- rev_mc_usu
- ria_ha_usu
- riv_tc_usu
- pop_ct_usu
- dor_pc_pva
- area
- area_fraction_used_for_aggregation
target_variables:
- discharge
test_basin_file: basin_list\regional_test.txt
test_end_date: 31/12/2023
test_start_date: 01/01/1980
train_basin_file: basin_list\regional_train.txt
train_dir: 
  C:\Users\ybrot\Desktop\course\UROP\GAGEii_modeling\runs\EA-LSTM_Regional_0604_152713\train_data
train_end_date: 31/12/2023
train_start_date: 01/01/1980
validate_every: 1
validate_n_random_basins: 200
validation_basin_file: basin_list\regional_test.txt
validation_end_date: 31/12/2023
validation_start_date: 01/01/1980
